//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyGin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasMateriaPrima
    {
        public int IdCompraMateriaPrima { get; set; }
        public Nullable<int> IdMateriaPrima { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<int> CantidadComprada { get; set; }
    
        public virtual MateriasPrimas MateriasPrimas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
