//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyGin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriasPrimas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MateriasPrimas()
        {
            this.ComprasMateriaPrima = new HashSet<ComprasMateriaPrima>();
            this.Produccion_MateriasPrimas = new HashSet<Produccion_MateriasPrimas>();
        }
    
        public int IdMateriaPrima { get; set; }
        public string DescripcionMateriaPrima { get; set; }
        public Nullable<int> StockMateriaPrima { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasMateriaPrima> ComprasMateriaPrima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produccion_MateriasPrimas> Produccion_MateriasPrimas { get; set; }
    }
}
