//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyGin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion_MateriasPrimas
    {
        public int IdProdu_MatPrima { get; set; }
        public Nullable<int> IdProduccion { get; set; }
        public Nullable<int> IdMateriasPrimas { get; set; }
        public Nullable<int> CantidadMateriaUsada { get; set; }
        public Nullable<int> IdProducto { get; set; }
    
        public virtual HistorialProduccion HistorialProduccion { get; set; }
        public virtual MateriasPrimas MateriasPrimas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
