//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyGin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.ComprasMateriaPrima = new HashSet<ComprasMateriaPrima>();
        }
    
        public int IdProveedor { get; set; }
        public string Nombre_razonSocial { get; set; }
        public string Apellido_TipoSoc { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasMateriaPrima> ComprasMateriaPrima { get; set; }
    }
}
